name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
codex/create-product-quotation-tool-chfqn1

codex/create-product-quotation-tool-db0tm4
Codex
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libjpeg-dev zlib1g-dev
codex/create-product-quotation-tool-chfqn1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

odex
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
Codex
      - name: Run tests
        run: pytest
